### ISSUE TITLE
Issues when new arch is enabled

### ISSUE THREAD

**Issue by alexferrermano** [ROKT/rokt-sdk-react-native#180]
After updating to 4.10.0 version I have this crash, when trying to render the view.

![Image](https://github.com/user-attachments/assets/55b703ab-be6e-4245-abf6-977f54a677be)

**Comment by thomson-t** [comment]
@alexferrermano can you share with us the ReactNative version and XCode environment details?

**Comment by thomson-t** [comment]
Thank you for the details, @alexferrermano. I was unable to reproduce the issue in a fresh project using the same version. It appears that the Fabric view configuration may not be functioning as expected. Could you please provide the output of `npx react-native info` so I can better understand your environment?

**Comment by alexferrermano** [comment]
Hello @thomson-t we are using typescript in our project. Could be the cause? With previous version 4.7.0 and RN 0.78.2 it was working okay. But looks now cannot identify the dependency.

**Comment by jamesnrokt** [comment]
Closing as this should be addressed with [4.10.2](https://github.com/ROKT/rokt-sdk-react-native/releases/tag/4.10.2) and there's been no activity on this issue recently. If you encounter any further problems please feel free to create a new issue.

**Comment by daveadapptor** [comment]
Still occurring on 4.12.2 on simulator.  Seems to be ok on device (so far).

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/cd088b8d-bc72-4dca-a421-83ed4d2db2cf" />
